version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=admin
      - DB_PASSWORD=123
      - DB_DATABASE=todo_app
      - JWT_SECRET=your-secret-key
    # depends_on:
    #   - postgres
    networks:
      - todo_network

  # postgres:
  #   image: postgres:15
  #   container_name: postgres_tasks
  #   restart: always
  #   environment:
  #     POSTGRES_USER: admin
  #     POSTGRES_PASSWORD: 123
  #     POSTGRES_DB: todo_app
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - todo_network

networks:
  todo_network:
    driver: bridge

volumes:
  postgres_data: